version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/redmine
  - source: redmine.conf
    destination: /etc/httpd/conf.d/
hooks:
  BeforeInstall:
    - location: tmp/stop_service.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: tmp/start_service.sh
      timeout: 300
      runas: root
