version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/redmine
hooks:
  BeforeInstall:
    - location: tmp/stop_service.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: tmp/stop_service.sh
      timeout: 300
      runas: root
